language: node_js
node_js:
    - "6"
    - "8"

before_script:

script:
    - npm run lint
    - ./run_tests

after_success:
    - npm install istanbul codecov
    - npm run cover
    - ./node_modules/.bin/codecov

sudo: false
